name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_herokuapp:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        MASTER_NODE_NAME: ${{ 'telegrambothost' }}

      run: |
        cd TelegramBotApp
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        
        heroku container:push web -a $MASTER_NODE_NAME
        heroku container:release web -a $MASTER_NODE_NAME
         